job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/anshulc55/Jenkins_Upgradev3.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}







// jon("First-Maven-Project-Via-DSL"){
//     description("First Maven Job gennerated  by DSL on ${new Date()}, this is simple maven project")


//     scm{
//         git("https://github.com/kashivirus/java-sample.git" , 'main')
//     }

//     triggers{
//         scm("* * * * *")
//     }

//     steps{
//         maven("clean package", 'maven-samples/single-module/pom.xml')
//     }

//     publishers{
//         archiveArtifacts "**/*.jar"
//     }
// }