job("First-Maven-Project-Via-DSL"){
    description("First Maven job generated by dsl on ${new Date()}, this project is small maven ")

    scm{
        git("https://github.com/kashivirus/java-sample.git" , 'main')
    }
    triggers{
        scm("* * * * *")
    }
    steps{
        maven("clean package" , "maven-samples/single-module/pom.xml")
    }
    publishers{
        archiveAertifacts "**/*.jar"
    }
}